language: generic
sudo: required
dist: trusty

install:
 - bash <(curl -sS https://nixos.org/nix/install)
 - source $HOME/.nix-profile/etc/profile.d/nix.sh

before_script:
  - nix-shell --pure --run 'cd third_party && ./build.sh'
  - nix-shell --pure --run './build.sh'

script:
  - nix-shell --pure --run 'build/taginfo-validate --help'
